### ISSUE TITLE
Correct anyWord writing

### ISSUE THREAD

**Issue by roddar92** [ExpandingDev/JSGFKit_Plus_Plus#10]
Dear colleagues,

I'm trying to make a grammar for `anyWord` token. Now it looks like this:

`<any_word> = (a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|r|s|t|u|v|w|x|y|z)+;`
`<rule> = <any_word>* a b <any_word>* c;`

But `anyWord` doesn't work in the last rule ('please a b c', 'a, b please c' etc.)
How could I fix my rule for correct working?

Sincerely yours,
Daria

**Comment by tsengia** [comment]
You are attempting to use JSGF for character-by-character matching, but JSGF is designed for word-by-word matching. You cannot use JSGF to create a regex. 
An example input that should satisfy your above `rule` would be:
`h e l l o a b w o r l d c` 
See how each character is actually a separate word.

I am curious as to why you are using such a grammar, I hope you are not passing it to a speech recognition toolkit. JSGF was designed to limit acceptable words that the user can input, which can help increase accuracy. By allowing for "any word" to be spoken, you will decrease recognition accuracy. I would recommend switching to a language model if you want to give the user more freedom in speaking.
