### ISSUE TITLE
Fail to build project

### ISSUE THREAD

**Issue by roddar92** [ExpandingDev/JSGFKit_Plus_Plus#9]
Dear colleagues,

I tried to build the library in Visual studio, but I have an exception of this kind:

`1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Checking Build System
2>------ Build started: Project: jsgfkit, Configuration: Debug Win32 ------
2>Building Custom Rule D:/JSGFKit_Plus_Plus/CMakeLists.txt
2>grammar.cpp
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(220): error C2079: 'ss' uses undefined class 'std::basic_stringstream<char,std::char_traits<char>,std::allocator<char>>'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(220): error C2440: 'initializing': cannot convert from 'const std::string' to 'int'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(220): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(224): error C2672: 'getline': no matching overloaded function found
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(224): error C2780: 'std::basic_istream<_Elem,_Traits> &std::getline(std::basic_istream<_Elem,_Traits> &,std::basic_string<_Elem,_Traits,_Alloc> &)': expects 2 arguments - 3 provided
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\string(160): note: see declaration of 'std::getline'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(224): error C2784: 'std::basic_istream<_Elem,_Traits> &std::getline(std::basic_istream<_Elem,_Traits> &,std::basic_string<_Elem,_Traits,_Alloc> &,const _Elem)': could not deduce template argument for 'std::basic_istream<_Elem,_Traits> &' from 'int'
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\string(149): note: see declaration of 'std::getline'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(224): error C2780: 'std::basic_istream<_Elem,_Traits> &std::getline(std::basic_istream<_Elem,_Traits> &&,std::basic_string<_Elem,_Traits,_Alloc> &)': expects 2 arguments - 3 provided
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\string(129): note: see declaration of 'std::getline'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(224): error C2784: 'std::basic_istream<_Elem,_Traits> &std::getline(std::basic_istream<_Elem,_Traits> &&,std::basic_string<_Elem,_Traits,_Alloc> &,const _Elem)': could not deduce template argument for 'std::basic_istream<_Elem,_Traits> &&' from 'int'
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\string(76): note: see declaration of 'std::getline'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(484): error C2131: expression did not evaluate to a constant
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(484): note: failure was caused by a read of a variable outside its lifetime
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(484): note: see usage of 'stringSize'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(590): error C2131: expression did not evaluate to a constant
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(590): note: failure was caused by a read of a variable outside its lifetime
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(590): note: see usage of 'stringSize'
2>D:\JSGFKit_Plus_Plus\src\grammar.cpp(801): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\string.h(133): note: see declaration of 'strcpy'
2>expansion.cpp
2>rule.cpp
2>matchinfo.cpp
2>matchresult.cpp
2>tag.cpp
2>unparsedsection.cpp
2>kleenestar.cpp
2>plusoperator.cpp
2>optionalgrouping.cpp
2>requiredgrouping.cpp
2>sequence.cpp
2>alternativeset.cpp
2>token.cpp
2>rulereference.cpp
2>Generating Code...
2>Done building project "jsgfkit.vcxproj" -- FAILED.
3>------ Build started: Project: ALL_BUILD, Configuration: Debug Win32 ------
3>Building Custom Rule D:/JSGFKit_Plus_Plus/CMakeLists.txt
4>------ Skipped Build: Project: INSTALL, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========`

What version of C++ did you use for this parser? Is the cause of that error is version mismatch?

Thanks in advance,
Daria

**Comment by tsengia** [comment]
I used a C++11 compiler. I have not tested compilation on Visual Studio, but I guess I should start running tests now!

**Comment by tsengia** [comment]
I was able to reproduce this issue, I need to clean up my code some, a fix should be ready in a few days.

**Comment by tsengia** [comment]
@roddar92 Try pulling the latest changes, I've gotten it to compile on Visual Studio 2017. If you can confirm that it compiles now I'll close the issue.

**Comment by roddar92** [comment]
Yep, now it compiles without problems. Great thanks! :)
